### PR TITLE
Use Next.js + Now v2

### PR DESCRIPTION
**Pull request by timneutkens**
- Migrates from Create React App to Next.js
- Uses API routes instead of needing a separate repository
- Next.js automatically exports the index page to static HTML that is served through the [Smart CDN](https://zeit.co/smart-cdn), meaning the site is fast around the world.
- The API routes are turned into serverless functions automatically.
- One API endpoint had caching inside the endpoint, converted that to leverage [`Cache-Control` with `stale-while-revalidate`](https://zeit.co/docs/v2/network/caching/?query=cache-control#stale-while-revalidate) that allows the response to be cached on the CDN layer instead. Making it fast around the world.
- Uses Dynamic routes for the API to automatically inject `username`.
- No longer uses `serve` / a docker container to host a static file.
- Uses `fetch` as it's polyfilled automatically by Next.js in older browsers (no need for axios)
- Uses 0 config deployments, meaning I only had to add the `env` property to make sure environment is injected. Besides that ZEIT Now automatically detects Next.js and builds it.

You'll likely want to install the ZEIT GitHub integration. This allows automatic deployments of PRs + when merged to the default branch (master in general) it'll automatically alias to the production url.

### CODE REVIEW

**Comment by sallar** [comment]
Thanks a lot @timneutkens this is fantastic! I have been meaning to clean up the project since it was done very quickly when I did it, but never got the chance and this is a great help. 
I'll try to deploy and set things up and will let you know how it goes. as I understand it, I just need to run `now` now and since the project name is the same as it was before, it will deploy to the same project? 

I'll merge this and start the deployment process.

**Comment by timneutkens** [comment]
Hey @sallar, it's probably best to go to zeit.co/dashboard and click `New Project` to link the GitHub repository. Then in the project you can go to `domains` and add  `github-contributions.now.sh`, this will set up auto-aliasing on push to master + fast rollback on revert.

**Comment by sallar** [comment]
Thanks! Will do. Btw you have added a theme called `YlGnBu` which is exactly the same as the GitHub one, is there something different?

**Comment by timneutkens** [comment]
@sallar I didn't add in anything new 🤔

**Comment by sallar** [comment]
@timneutkens scratch that Im dumb

**Comment by waldyrious** [comment]
I noticed the issue with the identical themes as well. I commented in #53; please add any insight I may be missing to explain the behavior.

**Pull request merged**
