### PR TITLE
Allow suport for separate route for viewing a user's contributions 

### LINKED ISSUE #55: Open web page with prefilled username
Hello, 

Is it possible to open web page with prefilled username and automatically generated chart?
For example 
https://github-contributions.now.sh/USERNAME

Thanks.

### PR DESCRIPTION
**Pull request by aviskarkc10**
fixes #55

### CODE REVIEW

**Comment by sallar** [comment]
@aviskarkc10 Im sorry I saw this too late. This project is using NextJS now and this PR wont work anymore. Unfortunately I have to close this. Thank you!

**Comment by aviskarkc10** [comment]
If you like the intent mind implementing something like this? Or I could contribute too?

**Comment by sallar** [comment]
Of course now that we're using NextJS, you can add a dynamic route and contribute. I would love to do it myself, but unfortunately I don't have much free time nowadays so a contribution would be amazing.

**Comment by aviskarkc10** [comment]
Okay. I might take a bit of time. But sure.

**Pull request closed without merging**
